#!/bin/sh
# Client backup script
# Ciarân Mooney
# 2018

EXCLUDE_LIST=/opt/exclude-list.lst

BACKUP_LOG=/var/log/backup.log
ERROR_LOG=/var/log/backup.error.log

# Check destination folder exists (ie wi-fi working, nfs working) 

# Log start time
echo -- >> $BACKUP_LOG
echo $(date) >> $BACKUP_LOG
echo -- >> $BACKUP_LOG

# Backup small files first
echo -- >> $BACKUP_LOG
echo BACKING UP SMALL FILES >> $BACKUP_LOG
rsync -rvz --exclude-from $EXCLUDE_LIST --times \
    --max-size=1M /home /mnt/backup > $BACKUP_LOG 2> $ERROR_LOG
# Log end time

# Log start time
# Backup larger files second
echo -- >> $BACKUP_LOG
echo BACKING UP LARGE FILES >> $BACKUP_LOG
rsync -rvz --exclude-from $EXCLUDE_LIST --times \
    --min-size=1M /home /mnt/backup > $BACKUP_LOG 2> $ERROR_LOG
# Log end time
# Set complete flag

# -r - recursive
# -v - verbose
# -z - compress files during transfer
# --times - compare times and copy if file modified

